"""empty message

Revision ID: 147feeab4df5
Revises: e8bc9b954fc3
Create Date: 2025-04-17 19:52:37.841302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147feeab4df5'
down_revision = 'e8bc9b954fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_from'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_to'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'posts', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
