"""empty message

Revision ID: 931a387a57c7
Revises: 147feeab4df5
Create Date: 2025-04-17 19:56:27.417851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931a387a57c7'
down_revision = '147feeab4df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_user_id_fkey', 'posts', ['user_id'], ['id'])

    # ### end Alembic commands ###
